spring:
  application:
    name: service-test-1
server:
  port: 8081
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: info